### ISSUE TITLE
Time axis, make outside lines togglable on and off

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1575]
We should create an API point that allows us to turn off / make invisible the outside lines on time axis (requested by slate users)
![screen shot 2015-02-04 at 1 49 23 pm](https://cloud.githubusercontent.com/assets/7527733/6050534/352a532c-ac75-11e4-8a0c-d740f977b61f.png)
http://jsfiddle.net/5rsjv76g/
In this, the line to the left of 2009 and right of 2012 should be able to become invisible

**Comment by jtlan** [comment]
I'll note that CSS pseudo-class selectors can be used to make the first and last marks disappear:
```CSS
.plottable .time-axis .tick-mark-container .tick-mark:first-of-type {
    stroke: none;
}
.plottable .time-axis .tick-mark-container .tick-mark:last-of-type {
    stroke: none;
}
```
http://jsfiddle.net/5rsjv76g/4/
