### ISSUE TITLE
Reading colors from CSS can lock up browser

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1834]
`Scale.Color` reads the colors from **plottable.css** by applying the `plottable-colors-N` css classes to a test `<div>`. If you happen to have this in your styles:
```CSS
div {
  background-color: yellow;
}
```
it will loop forever trying to load colors and lock up the browser.

No JSFiddle repro because, well, it'd lock up your browser.
